### ISSUE TITLE
Error in emotional attributes

### ISSUE THREAD

**Issue by bagustris** [MSP-UTD/MSP-Podcast_Challenge#2]
I tried to run the multitask learning version. After a day of running, it gives me the following error.

```
$ bash run_dim.sh
...
Epoch:  19
100%|█████████████████████████████████████████| 8545/8545 [52:27<00:00,  2.71it/s]
100%|███████████████████████████████████████| 19815/19815 [11:37<00:00, 28.39it/s]
train_aro : 0.6834 / train_dom : 0.6299 / train_val : 0.6587 / dev_aro : 0.6144 / dev_dom : 0.5399 / dev_val : 0.6963 /
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/data/github/MSP-Podcast_Challenge/eval_dim_ser.py", line 58, in <module>
    cur_wav_set = utils.WavSet(cur_wavs, wav_mean=wav_mean, wav_std=wav_std)
  File "/data/github/MSP-Podcast_Challenge/utils/dataset/dataset.py", line 44, in __init__
    self.max_dur = np.min([np.max([len(cur_wav) for cur_wav in self.wav_list]), self.upper_bound_max_dur*self.sampling_rate])
  File "/home/bagus/miniconda3/envs/msp-odyssey-2024/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/bagus/miniconda3/envs/msp-odyssey-2024/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

Maybe that error is related to the Python version. Which Python version did the organizer use for this baseline code?
@3loi  @ilucasgoncalves @MSP-UTD

**Comment by ilucasgoncalves** [comment]
Hello, thank you for raising this issue.

We are using Python `version 3.9.7`

I just tested the code again locally for me and it seems to be working fine. 

Looking at the error you display above it, seems like `ValueError: zero-size array to reduction operation maximum which has no identity` is indicating that you're attempting to perform a maximum reduction operation on an empty array. This can happen in the when the list comprehension `[len(cur_wav) for cur_wav in self.wav_list]` results in an empty list, meaning `self.wav_list` does not contain any elements or all elements in it are empty.

Make sure that `cur_utts` and `cur_labs` in `eval_dim_ser.py` [Line 55](https://github.com/MSP-UTD/MSP-Podcast_Challenge/blob/a9e1d2a18f2c9551c4e511482842e807e759019c/eval_dim_ser.py#L55) has contents when you are loading the `split_set` you will be evaluating (default case is "dev"). Additionally, check if the `labels_consensus.csv` file contains the sets you are trying to evaluate listed there.

Let me know if any of these solves the issue for you and please share what has worked. Thank you!

**Comment by bagustris** [comment]
Thanks for the quick feedback @ilucasgoncalves .

It seems that I tried to evaluate set `test3`, which is not available in `labels_consensus.csv.` If so, how to get a prediction for submission using this baseline?

I also wonder how you could test it quickly; mine needs hours on RTX3090. It doesn't give errors until epoch 19 above.

**Comment by ilucasgoncalves** [comment]
I see. Correct, test3 is not provided with 'labels_consensus.csv' since its a hidden set. 

I did not run the entire model again to run my testing, I only loaded the `dev` set and performed evaluation to check if code was properly working. My local machine also has a RTX3090 this is how long it took to load and evaluate for me:

**Comment by ilucasgoncalves** [comment]
I see. That is correct, test3 is not provided with 'labels_consensus.csv' since its a hidden set.

I did not run the entire model again to run my testing. I only loaded the dev set and performed evaluation to check if code was properly working. My local machine also has a RTX3090, this is how long it took to load and evaluate for me:

Loading:
100%|█████████████████████████████| 19815/19815 [00:29<00:00, 666.05it/s]
Evaluating:
100%|█████████████████████████████| 19815/19815 [08:34<00:00, 38.54it/s]


Regarding this question: "How to get a prediction for submission using this baseline?" As of now, you have to create your custom evaluation code to load test3 files, retrieve predictions, and save outputs for submission following the format described [here](https://lab-msp.com/MSP-Podcast_Competition/leaderboard.php).

I will work on a new custom evaluation code and upload it to the repository as soon as possible.

**Comment by ilucasgoncalves** [comment]
I have uploaded a new file (`eval_dim_ser_test3.py`) for custom evaluation on `test3`. 

You can execute it by pulling the code again and running `bash run_dim`, it should work directly and it will save results in a `results` folder located in the model path folder.
